version: "3.9"

services:
  # backend APIs
  hundred-api:
    build:
      context: ./hundred-api
      dockerfile: Dockerfile
    image: hundred-api:latest
    container_name: hundred-api
    environment:
      NODE_ENV: production
      MONGODB_URL: mongodb+srv://sabuj0338:Qr2JKNZ74HppnJa@cluster0.fe3fmv3.mongodb.net/hundred-api?retryWrites=true&w=majority
    ports:
      - 5100:3000
    # depends_on:
    #   - db
    restart: always

  # front-end admin panel
  hundred-admin:
    build:
      context: ./hundred-admin
      dockerfile: Dockerfile
    image: hundred-admin:latest
    container_name: hundred-admin
    environment:
      NODE_ENV: production
    ports:
      - 5200:4173
    depends_on:
      - hundred-api
    restart: always

  # front-end seller panel
  hundred-seller:
    build:
      context: ./hundred-seller
      dockerfile: Dockerfile
    image: hundred-seller:latest
    container_name: hundred-seller
    environment:
      NODE_ENV: production
    ports:
      - 5300:4173
    depends_on:
      - hundred-api
    restart: always

  # front-end web
  hundred-web:
    build:
      context: ./hundred-web
      dockerfile: Dockerfile
    image: hundred-web:latest
    container_name: hundred-web
    environment:
      NODE_ENV: production
    ports:
      - 5400:3000
    depends_on:
      - hundred-api
    restart: always

# volumes:
#   anime:
    # driver: local
