name: Deploy to DigitalOcean VPS

on:
  push:
    branches:
      - main  # Trigger the workflow on a push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to domain
      uses: appleboy/ssh-action@master
      with:
        username: ${{ secrets.VPS_USER }}
        host: ${{ secrets.VPS_HOST }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: 'cd /var/www/html && ./server_deploy.sh'