name: Deploy
 
on:
    push:
        branches:
            - main
jobs:
  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
 
    - name: Setup SSH connection
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy
      uses: fifsky/ssh-action@master
      with:
        command: | 
          cd /var/www/mandubukjahiz.com
          git pull origin main
        host: ${{ secrets.VPS_HOST }}
        port: ${{ secrets.VPS_PORT }}
        user: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY}}
        args: "-tt -vvv"